version: 0.2

phases:
  build:
    commands:
      - cd app
      - npm install
      - npm run build
      - zip -r ../aws-react-cognito.zip build

artifacts:
  files:
    aws-react-cognito.zip
  




